<script context="module">
  export const initialBalloons = [
    { id: "Brimble", height: "bottom" },
    { id: "Flakips", height: "down" },
    { id: "Groppie", height: "top" },
    { id: "Czostle", height: "middle" },
    { id: "Qualxir", height: "bottom" },
    { id: "Merilio", height: "up" },
    { id: "Grunhol", height: "bottom" },
    { id: "Yaaasss", height: "up" },
    { id: "Pouppah", height: "bottom" },
    { id: "Jowdwac", height: "bottom" },
    { id: "Heltchu", height: "bottom" },
    { id: "Flowdar", height: "bottom" },
    { id: "Oeoeooo", height: "bottom" },
    { id: "Nopnope", height: "bottom" },
    { id: "Regreps", height: "up" },
    { id: "Trimble", height: "bottom" },
    { id: "Fuakips", height: "down" },
    { id: "Grippie", height: "top" },
    { id: "Czogtle", height: "middle" },
    { id: "Qualyir", height: "bottom" },
    { id: "Merilzo", height: "up" },
    { id: "Grunhom", height: "bottom" },
    { id: "Naaasss", height: "up" },
    { id: "Piuppah", height: "bottom" },
    { id: "Jokdwac", height: "bottom" },
    { id: "Helcchu", height: "bottom" },
    { id: "Flowear", height: "bottom" },
    { id: "Oeoeoio", height: "bottom" },
    { id: "Nopnopt", height: "bottom" },
    { id: "Degreps", height: "up" }
  ];
</script>
